### ISSUE TITLE
outofmemory

### ISSUE THREAD

**Issue by Natalcia** [jaredmeister/OutOfMemory#1]
nie da sie używać bo outofmemory wali napraw

**Comment by CriSSuFM** [comment]
Próbowałaś przydzielić więcej pamięci RAM?

**Comment by Natalcia** [comment]
Tak i dalej to samo

**Comment by k0l0r3k99** [comment]
Do u speak English? I don't understand what u said

**Comment by Natalcia** [comment]
Thanks to #3 I finally got it working! 🥰
